# Generated by Django 5.0.1 on 2024-01-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doorman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=194, verbose_name='Full Name')),
                ('SSN', models.CharField(max_length=9, verbose_name='SSN')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Contact Phone Number')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('basic_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Doorman',
                'verbose_name_plural': 'Doormen',
                'db_table': 'doorman',
            },
        ),
    ]
